class { 'tor':
  socksport           => [ '0' ],
  sockspolicy         => [ 'reject *' ],
  orport              => [ '443 NoListen', '10.2.3.4:9090 NoAdvertise' ],
  address             => '10.2.3.4',
  outboundbindaddress => '10.2.3.4',
  nickname            => 'ididnteditheconfig',
  myfamily            => '10.2.3.5',
  bandwidthrate       => '100 MB',
  bandwidthburst      => '200 MB',
  numcpus             => '2',
  contactinfo         => 'Random Person <nobody AT example dot com>',
  dirport             => [ '80 NoListen', '10.2.3.4:9091 NoAdvertise' ],
  exitpolicy          => [ 'reject *:*' ],
  hidden_services     => [ ],
  dnsport             => [ '53', '5353 IsolateClientAddr' ],
  transport           => [ '7001', '7002 IsolateDestAddr' ],
  virtualaddrnetwork  => [ '100.64.0.0/10' ],
  virtualaddrnetwork6 => [ '[fc00::]/7' ],
  automaphosts        => true,
}
